urls.py
from django.conf.urls import *
from django.conf import settings
from tags import views as tags

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    (r'^accounts/logout$', 'django.contrib.auth.views.logout', {'next_page' : '/'}),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^tagr\.user\.js', tags.gmscript),
    (r'^tags/', tags.tags),
    (r'^add/', tags.add),
    (r'^c/', tags.getcsrf),
    (r'^export/', tags.export),
    (r'^edit/(?P<url>.+)', tags.add),
    (r'^del/(?P<url>.+)', tags.delete),
    (r'^bibtex/(?P<url>.+)', tags.bibtex),
    (r'^purloin/(?P<id>.+)', tags.purloin),
    (r'^import/', tags.load),
    (r'^v/(?P<shurl>.+)?', tags.view),
    (r'^r/(?P<shurl>.+)?', tags.shurlect),
    (r'^s/(?P<hash>.+)?', tags.getSnapshot),
    (r'^$', tags.show),                                       # list all (except private)
    (r'^t/(?P<tags>.+)?', tags.show),                         # ... filtered by tags
    (r'^u/(?P<user>.+)/$', tags.show),                        # list only users items
    (r'^u/(?P<user>.+)/(?P<tags>.+)?$', tags.show),           # ... filtered by tags

    # Uncomment the next line to enable the admin:
    #(r'^admin/', include(admin.site.urls)),
)

if settings.DEV_SERVER:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PATH}),
    )

tags/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django_mongokit import connection
from django_mongokit.document import DjangoDocument
from counter import getNextVal
import datetime

class Bookmark(DjangoDocument):
    class Meta:
        verbose_name_plural = "Bookmarks"

    collection_name = 'bookmarks'
    structure = {
        'seq': int,
        'tags': [unicode],
        'user': unicode,
        'url': unicode,
        'created': datetime.datetime,
        'private': bool,
        'title': unicode,
        'notes': unicode,
        'snapshot': [unicode],
        #'author': unicode,
        #'year': unicode,
        }

    default_values = {
        'created': datetime.datetime.utcnow,
        'seq': getNextVal,
        }

    use_dot_notation = True

    indexes = [
        {'fields': ['user','url','created', 'seq']},
        ]
    def __unicode__(self):
        return self.title

connection.register([Bookmark])

tags/forms.py
from django import forms
from django.conf import settings
from django.forms.widgets import HiddenInput

class AdvancedEditor(forms.Textarea):
	class Media:
		js = (settings.MEDIA_URL+'/js/tinymce/tiny_mce.js',)

	def __init__(self, language=None, attrs=None):
		self.language = language or settings.LANGUAGE_CODE[:2]
		self.attrs = {'class': 'advancededitor'}
		if attrs: self.attrs.update(attrs)
		super(AdvancedEditor, self).__init__(attrs)

class AddBookmarkForm(forms.Form):
    url =forms.CharField(required=True, label="UR Location")
    title = forms.CharField(required=False, label="Title")
    tags = forms.CharField(required=False, label="Tags")
    suggestedTags = forms.CharField(required=False, label="Suggested Tags")
    notes = forms.CharField(required=False, widget=AdvancedEditor(), label="Notes")
    private = forms.BooleanField(required=False, label="Private")
    popup = forms.IntegerField(required=False)
    page = forms.CharField(required=False, widget=HiddenInput)

class ImportDeliciousForm(forms.Form):
    exported = forms.FileField(required=True, label="Upload Delicious export")

tags/views.py
from models import Bookmark
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render_to_response
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.exceptions import ObjectDoesNotExist
from django.core.context_processors import csrf
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.template import RequestContext
from django.views.decorators.gzip import gzip_page
from django.conf import settings
import conf
from utils import unescape
from tags.forms import AddBookmarkForm, ImportDeliciousForm
from lxml import etree
from BeautifulSoup import BeautifulSoup, Comment
from datetime import datetime
from urlparse import urljoin, urlparse, urlunparse
from counter import getNextVal
from baseconv import base62
import urllib2, re, urllib, json, pymongo, hashlib, gzip, os
from itertools import ifilterfalse, imap

from django_mongokit import get_database
database = get_database()
collection = database['bookmarks']

#TODO split bookmarking and url tagging

def sanitizeHtml(value, base_url=None):
    rjs = r'[\s]*(&#x.{1,7})?'.join(list('javascript:'))
    rvb = r'[\s]*(&#x.{1,7})?'.join(list('vbscript:'))
    re_scripts = re.compile('(%s)|(%s)' % (rjs, rvb), re.IGNORECASE)
    validTags = 'p i strong b u a h1 h2 h3 pre br img'.split()
    validAttrs = 'href src width height'.split()
    urlAttrs = 'href src'.split() # Attributes which should have a URL
    soup = BeautifulSoup(value)
    for comment in soup.findAll(text=lambda text: isinstance(text, Comment)):
        # Get rid of comments
        comment.extract()
    for tag in soup.findAll(True):
        if tag.name not in validTags:
            tag.hidden = True
        attrs = tag.attrs
        tag.attrs = []
        for attr, val in attrs:
            if attr in validAttrs:
                val = re_scripts.sub('', val) # Remove scripts (vbs & js)
                if attr in urlAttrs:
                    val = urljoin(base_url, val) # Calculate the absolute url
                tag.attrs.append((attr, val))

    return soup.renderContents().decode('utf8')

def show(request,tags=[],user=None):
    if user:
        try: user = User.objects.get(username=user)
        except ObjectDoesNotExist: return HttpResponse("no access")

    try: limit=int(request.GET.get('limit'))
    except TypeError, ValueError: limit=25

    try: page=int(request.GET.get('page'))
    except TypeError, ValueError: page=1

    baseurl=request.path.split('?')[0]
    plist=baseurl.split('/')
    if plist[1]=='t':
        path='/'
    else:
        path='/'.join(plist[:-1])

    db = get_database()[Bookmark.collection_name]
    query={}
    if not user or request.user!=user:
        query['private']=False
    if user:
        query['user']=unicode(user)
    if tags:
        tags=urllib.unquote_plus(tags).split(' ')
        query['tags']={'$all': tags}

    order=[('created', pymongo.DESCENDING)]
    res=db.find(query)

    tagcloud=[]
    if (tags or user) and request.GET.get('format','') == '':
        timetags={}
        for item in res:
            d=item['created'].strftime("%Y-%m-%d")
            timetags[d]=timetags.get(d,{})
            for t in item['tags']:
                if t in tags: continue
                timetags[d][t]=timetags[d].get(t,0)+1
        tagcloud=[(k.replace('&','&amp;'), sorted(v.items()))
                  for k, v
                  in sorted(timetags.items())]

    res=db.find(query,sort=order)
    total=res.count()
    paginator = Paginator(res, limit)
    try:
        res = paginator.page(page)
    except (EmptyPage, InvalidPage):
        res = paginator.page(paginator.num_pages)

    if request.GET.get('format','') == 'json':
        res=[{'url': unicode(obj['url']),
              'title': unicode(obj['title']),
              'created': tuple(obj['created'].timetuple()),
              'private': obj['private'],
              'notes': unicode(unescape(obj['notes'])),
              'tags': obj['tags']
              } for obj in res.object_list]
        if request.GET.get('j')==None:
            return HttpResponse(json.dumps(res),mimetype="application/json")
        return HttpResponse("var omnom_posts = "+json.dumps(res)+";",mimetype="text/javascript")

    if request.GET.get('format','') == 'atom':
        tpl='atom.xml'
    else:
        tpl='list.html'

    res.object_list=[{'seq': obj['seq'],
                      'url': obj['url'],
                      'user': obj['user'],
                      'title': obj['title'],
                      'created': obj['created'],
                      'private': obj['private'],
                      'snapshot': '' if not obj.get('snapshot') else obj.get('snapshot')[0],
                      'notes': unescape(obj['notes']),
                      'tags': map(unicode, obj['tags'])
                      } for obj in res.object_list]
    return render_to_response(tpl,
                              { 'items': res,
                                'limit': limit,
                                'total': total,
                                'tags': [(tag, "+".join(t for t in tags if not t == tag) if len(tags)>1 else path) for tag in tags] if tags else [],
                                'tagcloud': json.dumps(tagcloud),
                                'baseurl': baseurl,
                                'path': request.path},
                              context_instance=RequestContext(request) )

apacheFix=re.compile(r'(https?://?)\w*')
def fixApacheMadness(url):
    m=re.match(apacheFix,url)
    if m and m.group(1)[-2:] != '//':
        url="%s/%s" % (m.group(1),url[len(m.group(1)):])
    return url

utmRe=re.compile('utm_(source|medium|campaign|content)=')
def urlSanitize(url):
    # removes annoying UTM params to urls.
    pcs=urlparse(urllib.unquote(url))
    tmp=list(pcs)
    tmp[4]='&'.join(ifilterfalse(utmRe.match, pcs.query.split('&')))
    return urlunparse(tmp)

def purloin(request,id):
    try: id = int(id)
    except: return HttpResponse("error: not an integer: %s" % id)
    db = get_database()[Bookmark.collection_name]
    fromobj=db.find_one({'seq': id})
    if not fromobj:
        return HttpResponse("error: no such object")

    obj=db.Bookmark({'url': fromobj['url'],
                     'seq': getNextVal('seq'),
                     'user': unicode(request.user),
                     'created': datetime.today(),
                     'private': False,
                     'title': fromobj['title'],
                     'notes': unicode(""),
                     'tags': fromobj['tags'],
                     'snapshot': fromobj.get('snapshot', []),
                     })
    obj.save()
    return HttpResponseRedirect("/v/%s" % base62.from_decimal(obj['seq']))

def add(request,url=None):
    done=False
    if request.method == 'GET':
        form = AddBookmarkForm(request.GET)
    elif request.method == 'POST':
        form = AddBookmarkForm(request.POST)
        if request.GET.get('close'):
            done=True
    else:
        return HttpResponse("wrong method")
    try: user=User.objects.get(username=request.user)
    except ObjectDoesNotExist:
        return HttpResponseRedirect("/accounts/login")
    suggestedTags=set()
    db = get_database()[Bookmark.collection_name]
    if request.REQUEST.get("dontsave", 0) or not form.is_valid() or form.cleaned_data['popup']:
        if url: # try to edit an existing bookmark?
            url=fixApacheMadness(url)
            url=urlSanitize(url)
            try:
                obj=db.find_one({'url':url, 'user': unicode(user)})
            except ObjectDoesNotExist: obj=None
            if obj: # yes, edit an existing bookmark
                data={ 'url' : url,
                       'title' : obj['title'],
                       'tags' : ' '.join([unicode(x) for x in obj['tags']]),
                       'notes' : obj['notes'],
                       'private' : obj['private'],
                       }
                if form.is_valid():
                    data['popup']=form.cleaned_data.get('popup')
                try:
                    suggestedTags=set(suggestTags(data['url']).keys())
                except: suggestedTags=set()
                try:
                    suggestedTags.update(getCalaisTags(data['notes']))
                except: pass
                form = AddBookmarkForm(data)
        try:
            suggestedTags=set(suggestTags(form.cleaned_data['url']).keys())
        except: pass
        try:
            suggestedTags.update(getCalaisTags(form.cleaned_data['notes']))
        except: pass
        if hasattr(form, "cleaned_data"):
            tpl='add.html' if form.cleaned_data.get('popup','') == 1 else 'addWidget.html'
        else:
            tpl='add.html'
        return render_to_response(tpl,
                                  { 'form': form,
                                    'suggestedTags': sorted(suggestedTags) },
                                  context_instance=RequestContext(request))

    # ok we have some valid form. let's save it.
    url=urlSanitize(form.cleaned_data['url'])
    try:
        obj=db.one({'url': url, 'user': unicode(user)})
    except ObjectDoesNotExist:
        obj=None

    snapshot=form.cleaned_data['page'].encode('utf8')
    if snapshot:
        hash=hashlib.sha512(snapshot).hexdigest()
        fname="%s/snapshots/%s" % (settings.BASE_PATH, hash)
        dump=gzip.open(fname,'wb')
        dump.write(snapshot)
        dump.close()
        snapshot=hash
    if obj: # edit
        obj=db.Bookmark(obj)
        if form.cleaned_data['private']: obj['private']=form.cleaned_data['private']
        if form.cleaned_data['title']: obj['title']=sanitizeHtml(form.cleaned_data['title'])
        if form.cleaned_data['notes']: obj['notes']=sanitizeHtml(form.cleaned_data['notes'])
        if form.cleaned_data['tags']: obj['tags']=map(sanitizeHtml, form.cleaned_data['tags'].split(" "))

templates/add.html
{% extends "base.html" %}
{% load tagger %}
{% block scripts %}
<script type="text/javascript" src="{%media_url%}/js/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="{%media_url%}/js/addbookmark.js"></script>
<script type="text/javascript" src="{%media_url%}/js/jquery.1.4.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $(".suggestedTag").focus( function(event) { $(this).blur(); return false; });
    $(".suggestedTag").click( function(event) {
        var self=$(this)
         if(document.addForm.tags.value) {
              document.addForm.tags.value+=' '; }
         document.addForm.tags.value+=self.attr('name');
         self.hide();
    });
});
</script>
{% endblock %}

{%block content%}
<h2>add entry</h2>
<form class="xfolkentry" name="addForm" action="{% root_url %}/add/" method="get">
  <table>
    <tr><td>{{form.url.label_tag}}</td><td>{{form.url}}</td></tr>
    <tr><td>{{form.title.label_tag}}</td><td>{{form.title}}</td></tr>
    <tr><td>{{form.notes.label_tag}}</td><td>{{form.notes}}</td></tr>
    <tr><td>{{form.tags.label_tag}}</td><td>{{form.tags}}</td></tr>
    <tr><td>Recommended Tags</td><td width="598px">
        {% for tag in suggestedTags %}
        <span class="suggestedTag" name="{{tag}}">{{tag}}{%if not forloop.last%}, {%endif%}</span>
        {%empty%}
        None
        {% endfor %}
    </td></tr>
    <tr><td>{{form.private.label_tag}}</td><td>{{form.private}}</td></tr>
    <tr><td /><td><input type="submit" value="save" /></td></tr>
  </table>
  {{form.page}}
</form>
{%endblock%}

templates/addWidget.html
{% load tagger %}
<link rel="stylesheet" type="text/css" media="all" href="{% media_url %}/css/gmstyle.css" />
<form class="xfolkentry" name="addForm" id="tagr_addForm" action="{% root_url %}/add/" method="get">
  <table>
    <tr><td>{{form.url.label_tag}}</td><td>{{form.url}}</td></tr>
    <tr><td>{{form.title.label_tag}}</td><td>{{form.title}}</td></tr>
    <tr><td>{{form.notes.label_tag}}</td><td>{{form.notes}}</td></tr>
    <tr><td>{{form.tags.label_tag}}</td><td>{{form.tags}}</td></tr>
    <tr><td>Recommended Tags</td><td id="tagr_tagsuggestion" width="588px">
        {% for tag in suggestedTags %}
        <span class="suggestedTag" name="{{tag}}">{{tag}}</span>{%if not forloop.last%} {%endif%}
        {%empty%}
        None
        {% endfor %}
    </td></tr>
    <tr><td>{{form.private.label_tag}}</td><td>{{form.private}}</td></tr>
    <tr><td /><td><input type="submit" value="save" /><input type="button" value="cancel" /></td></tr>
  </table>
  {{form.page}}
  {% csrf_token %}
</form>

templates/base.html
{% load tagger %}<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="hu" xml:lang="hu">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="en" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <title>{% block title %}[!] tagger {% endblock %}</title>
    <meta name="robots" content="noarchive,noindex,nofollow">
    {% block rss %}
    {% endblock %}
    {% block scripts %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" media="all" href="{% media_url %}/css/style.css" />
    {% block styles %}
    {% endblock %}
</head>
<body>
	<div id="auth" class="menu">
	{% if user.is_authenticated %}
		<a href="{%root_url%}/accounts/password/change/">{{ user.username }}</a>
		<a href="{%root_url%}/accounts/logout/">Logout</a>
	{% else %}
		<a href="{%root_url%}/accounts/login/">Login</a>
		<a href="{%root_url%}/accounts/register/">Register</a>
	{% endif %}
	</div>

	<div id="menu" class="menu">
	{% if user.is_authenticated %}
		<a href="{%root_url%}/">All</a>
		<a href="{%root_url%}/u/{{user}}/">Mine</a>
		<a href="{%root_url%}/import/">Import</a>
	{%endif%}
   <a href="javascript:var selection = '';if (window.getSelection) {selection = window.getSelection();} else if (document.getSelection) {selection = document.getSelection();} else if (document.selection) {selection = document.selection.createRange().text;};x=document;a=encodeURIComponent(x.location.href);t=encodeURIComponent(x.title);d=encodeURIComponent(selection);open('http://{{request.get_host}}/add/?popup=1&amp;url='+a+'&amp;title='+t+'&amp;notes='+d,'tagger','modal=1,status=0,scrollbars=1,toolbar=0,resizable=1,width=730,height=465,left='+(screen.width-730)/2+',top='+(screen.height-425)/2);void 0;">Bookmarklet</a>
		<a href="{%root_url%}/tagr.user.js">Userscript</a>
	</div>

{% block content %}
{% endblock %}
{% block other_content %} {% endblock %}
  </div>
</body>
</html>

templates/export.html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>
   {% for b in bookmarks %}
   <DT><A HREF="{{b.url}}" ADD_DATE="{{b.created|date:"U"}}" TAGS="from:omnom {{b.tags}}">{{b.title}}</A>
   <DD>{{b.notes|safe}}
   {% endfor %}
</DL><p>

templates/import.html
{% extends "base.html" %}{%load tagger%}
{%block content%}
<form enctype="multipart/form-data" method="post" action="/import/">
  {{form}}
  {% csrf_token %}
  <br />
  <input type="submit" value="Import">
</form>
{%endblock%}

templates/list.html
{% extends "base.html" %}{%load tagger%}
{%block scripts%}
   {%if tagcloud%}
      <!--[if IE]><script language="javascript" type="text/javascript" src="../../include/excanvas.js"></script><![endif]-->
      <script type="text/javascript" charset="utf-8" src="{%media_url%}/js/jquery.js"></script>
      <script type="text/javascript" charset="utf-8" src="{%media_url%}/js/jquery.sparkline.js" ></script>
      <script type="text/javascript" charset="utf-8" src="{%media_url%}/js/jquery-ui-p.min.js"></script>
      <script type="text/javascript" charset="utf-8" src="{%media_url%}/js/jquery.event.wheel.js"></script>
      <script type="text/javascript" charset="utf-8" src="{%media_url%}/js/tagcloud.js"></script>
      <script type="text/javascript" charset="utf-8" src="{%media_url%}/js/timecloud.js"></script>
      <script type="text/javascript">
        $(document).ready(function() {
               $("#timecloud").timecloud({"timecloud":{{tagcloud|safe}},
                                          "start": -1,
                                          "sparklineStyle": { type:'line',
                                                              lineColor:'Navy',
                                                              height:'30px',
                                                              chartRangeMin: '0',
                                                              width:'300px' },
                                          "urlprefix": '{{baseurl}}{%if tags%}+{%endif%}'});
	});
	function getBibTeX(url) {
		//$("#bibtexloadbox").show('slow');
		$.getJSON("{%root_url%}/bibtex/"+url, function(data) {
			// $("#bibtexloadbox").hide();
			$("#bibtextext").val(data.bibtex);
			$("#bibtexbox").show('slow');
		});
	}
      </script>
   {%endif%}
{%endblock%}

{%block rss%}
    <link rel="alternate" type="application/atom+xml" title="Atom feed" href="{{baseurl}}?format=atom">
{%endblock%}

{%block styles%}
   {%if tagcloud%}
    <link rel="stylesheet" type="text/css" media="all" href="{% media_url %}/css/tagcloud.css" />
   {%endif%}
{%endblock%}

{%block content%}
<br style="clear: both" />
{%if tagcloud %}
<div id="timecloud"></div>
{%endif%}
{%if tags%}
<ul class="tags">
{%for tag, link in tags%}
<li><a rel="tag" href="{{link}}">{{tag}}</a></li>
{%endfor%}
</ul>
{%endif%}

<div id="totalcontainer">{% include "paging.html" %}
<span id="total">{{total}}</span></div>
{% for item in items.object_list %}
<div class="xfolkentry">
  <div class="actions">
	<a onclick="getBibTeX('{{item.url|urlencode}}');">BibTeX</a>
  {%if user.username == item.user %}
	<a href="{%root_url%}/edit/{{item.url|urlencode}}">Edit</a>
	<a href="{%root_url%}/del/{{item.url|urlencode}}">Delete</a>
  {%else %}
	{% if user.is_active %}
	<a href="{%root_url%}/purloin/{{item.seq}}">Purloin</a>
	{% endif %}
  {%endif%}
  {%if item.snapshot %}
   <a href="{%root_url%}/s/{{item.snapshot}}">snapshot</a>
  {%endif%}
  <a href="{%root_url%}/r/{{item.seq|shorturl}}">shorturl</a>
  </div>
  <div><a class="taggedlink" href="{{item.url}}">{{item.title|striptags}}</a></div>
  <div class="description">{{item.notes|striptags|urlize|linebreaks}}</div>
  <div class="meta">
    <span class="tagcontainer">
    {%for tag in item.tags%}
        {%if baseurl == '/' %}
        <a rel="tag" href="/t/{{tag}}">{{tag}}</a>
        {%else%}
        <a rel="tag" href="{{baseurl}}{%if tags%}+{%endif%}{{tag}}">{{tag}}</a>
        {%endif%}
    {%endfor%}
    </span>


    <div>
       <span class="datetime">{{item.created|date:"d/m/Y h:m:s"}}</span>
       <span class="username"><a href="{%root_url%}/u/{{item.user}}/">{{item.user}}</a></span>
       {% if item.rel %}
         <span class="hoverhide">
         <small>Related Bookmarks</small>
            <ul class="related_bm">
               {% for w, doc in item.rel %}
               <li>{{w|floatformat:"-2"}} <a href="{{doc.shurl}}">{{doc.title}}</a></li>
               {% endfor %}
            </ul>
         </span>
       {% endif %}
    </div>
  </div>
</div>


<div id="bibtexloadbox" class="dialog">
Loading...
</div>
<div id="bibtexbox" class="dialog">
	<textarea id="bibtextext" style="width: 100%; min-height: 200px;">

	</textarea>
	<a onclick="$('#bibtexbox').hide('slow');">Close</a>
</div>


{%endfor%}
{% include "paging.html" %}
{%endblock%}

templates/view-bare.html
{%load tagger%}

<style>
#omnom_widget * { font-size: 12px; color: #666; font-family: Verdana,Arial,Helvetica,sans-serif; text-align: justify; border: none; padding: 0; margin: 0; text-align:left; vertical-align:top; background: #fff; font-weight: normal; }
#omnom_widget div, #omnom_widget input, #omnom_widget p{ margin:0; padding:0; background: none; }
#omnom_widget a { text-decoration: none; color: #4c846e; }
#omnom_widget a[href]:hover { text-decoration: none; color: #000; }
#omnom_widget .tagcontainer { font-size: 90%; width: 300px; float: right; margin-right: 10px; float: right;}
#omnom_widget .taggedlink { color:   #09402a; }
#omnom_widget .xfolkentry { overflow:  hidden; padding:  12px 0 12px 65px; }
#omnom_widget div { margin: 4px 0px 0px 0px; }
#omnom_widget { margin: 10px; border: 0; padding: 0; overflow:hidden; padding:12px 0 12px 10px; -moz-border-radius: 0.5em; -webkit-border-radius: 0.5em;}
#omnom_widget [rel=tag] { background-color: #ddd; margin-left: 5px; margin-bottom: 2px; padding: 1px; float: right; }
#omnom_widget [rel=tag]:hover { text-decoration: none; color: #fff; }
#omnom_widget input, #omnom_widget textarea { border: 1px solid #0088DD; background: #FFFFFF; color: #666666; padding-right:10px; margin: 3px 0 0 0;}
#omnom_widget .button { border: 1px solid #0088DD; background: #FFFFFF; color: #666666; padding: 0px 6px 0px 6px; margin: 4px; text-decoration: none; color: #666666;}
#omnom_widget a { text-decoration: none; color: #0088dd; }
#omnom_widget a[href]:hover { text-decoration: none; color: #000; }
#omnom_widget input[type=text], #omnom_widget textarea { width: 97%; }
#omnom_widget .suggestedTag { cursor: pointer ; color: #0088dd; }
#omnom_widget .xfolkentry [rel=tag] {float: right; }
#omnom_widget label { margin-right: 6px; }
</style>
<div id='omnom_widget' class="xfolkentry">
<table><tbody>
<tr><td><label for="id_title">Title</label></td><td ><strong><a class="taggedlink" href="{{item.url}}">{{item.title|safe}}</a></strong></td></tr>
<tr><td><label for="id_notes">Notes</label></td><td><textarea name="notes" cols="40" rows="8" id="id_notes">{{item.notes|safe}}</textarea></td></tr>
<tr><td><label for="id_tags">Tags</label></td><td>
  <div class="meta">
    <span class="tagcontainer">
    {%for tag in item.tags%}
        <a rel="tag" href="/t/{{tag}}">{{tag}}</a>
    {%endfor%}
    </span> ... on {{item.created}}
  </div>
</td></tr>
<tr><td><label for="id_url">URL</label></td><td>{{item.url}}</td></tr>
<tr><td><label for="id_url">Shorturl</label></td><td><a href="{% if request.is_secure %}https{% else %}http{% endif %}://{{request.get_host}}/r/{{item.shurl}}">{% if request.is_secure %}https{% else %}http{% endif %}://{{request.get_host}}/r/{{item.shurl}}</a></td></tr>
<tr><td></td><td>
  {%if user.username == item.user %}
  <div>
  <a href="{%root_url%}/edit/{{item.url|urlencode}}">Edit</a> | <a href="{%root_url%}/del/{{item.url|urlencode}}">Delete</a>{% if item.snapshot %} | <a href="{%root_url%}/s/{{item.snapshot}}">Snapshot</a>{%endif%}
  </div>
  {%endif%}
</td></tr>
</tbody></table>
</div>